baseURL = "https://raphaelsilv.github.io/raphael-hugo-pages/"
languageCode = "The language code for the language the website is written in"
title = "Raphael Ramos | Code Insights"
theme = "aether"
googleAnalytics = "Your google analytics tracking ID - optional"
disqusShortname = "basquiatraphaeu"
tags = ["Blog", "Personal", "Raphael", "Shell", "Simple", "Code", "Programmer", "Technical", "Github", "UFSC", "C++", "Shell"]
features = ["Responsive", "Highlight.js", "KaTeX", "Google analytics", "Disqus"]
min_version = "0.01"
publishDir = "public"

[params]
brand = "By: Raphael Ramos"
description = "The website's description"
homeimg = "img/fancy-pants.jpg"
bgimg = "img/ignasi_pattern_s.png"

[author]
name = "Raphael Ramos"
homepage = "https://www.linkedin.com/in/raphaelramosdasilva/"
